### ISSUE TITLE
Link to laxarjs.org/docs rather than GitHub

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/generator-laxarjs2#1]
When linking to docs from the prompt or the generated application, we should link to the latest http://laxarjs.org/docs/ for the corresponding LaxarJS major version, and not to the manuals / README on GitHub.

Similar Ticket for v1.x generator: 
https://github.com/LaxarJS/generator-laxarjs/issues/21

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
