### ISSUE TITLE
app template: use import instead of require for adapters

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/generator-laxarjs2#15]
The result for an application using for example angular should be:
```javascript
import * as angularAdapter from 'laxar-angular-adapter';
```
instead of:
```javascript
var angularAdapter = require( 'laxar-angular-adapter' );
```

https://github.com/LaxarJS/generator-laxarjs2/blob/master/generators/app/index.js#L121

**Comment by alex3683** [comment]
Fixed on `master` (`v2.0.0`).
