### ISSUE TITLE
Update template dependencies for webpack 3 (was: App template: Update to webpack 3)

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/generator-laxarjs2#17]
Currently the `webpack-dev-server` is still not webpack 2 aware. As soon as this is no longer an issue, we should update.
See webpack/webpack-dev-server#932

**Comment by jpommerening** [comment]
https://github.com/webpack/webpack-dev-server/pull/946#issuecomment-313593956

**Comment by x1B** [comment]
After giving it a quick spin against a LaxarJS2/Vue.js app, it definitely _feels_ faster now. HMR also still working, so I guess this is go.

**Comment by alex3683** [comment]
Are we treating this as a breaking change? (See https://github.com/LaxarJS/laxar/issues/470#issuecomment-313693688)

**Comment by x1B** [comment]
@alex3683 I think, for a change to the generator to be breaking, it would mean that a new version can no longer generate widgets/activities for an application created with an older version. So this would not be breaking.

**Comment by alex3683** [comment]
@x1B Okay, that is in accordance to what @jpommerening and me discussed yesterday.

**Comment by alex3683** [comment]
Changed the title, since more plugins and other dependencies needed to be lifted to be compatible with webpack 3.

**Comment by alex3683** [comment]
Implemented on `master` (`v2.1.0`).

### Upgrade Information

Since webpack 3 was [announced to be non-breaking](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b), we assume that there will be no problems with this change. Our tests showed none.
By default the new `ModuleConcatenationPlugin` for _Scope Hoisting_ is loaded. Feel free to remove it in the generated app, if you don't want it.
