### ISSUE TITLE
Templates: Change default license expression from "none" to "UNLICENSED"

### ISSUE THREAD

**Issue by x1B** [LaxarJS/generator-laxarjs2#23]
We should offer the value `"UNLICENSED"` as default instead of `"none"` and set `"private": true` if unlicensed is used.

**Comment by x1B** [comment]
For Details:

- https://github.com/npm/npm/issues/8291#issuecomment-113649755
- https://github.com/npm/npm/issues/8773#issuecomment-149340965
- https://github.com/npm/npm/issues/8918#issuecomment-151338696

**Comment by alex3683** [comment]
Fixed on `master` (`v2.1.0`).

### Upgrade Information

The new default license is now `"UNLICENSED"`, and if that is chosen, the package visibility for npm is set to _private_ (`"private": true` in `package.json`). If that is not what you want, simply remove the `"private"` entry from the `package.json` after creation of an artifact.
