### ISSUE TITLE
overwritten default paths should be taken into account

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/generator-laxarjs2#27]
The default paths where webpack resolves widgets and controls can be overwritten by adding a file `laxar.config.js` to the application directory and exporting custom directories there. I think it would be great if the generator would also read that file (if present), and use the directories defined there as default directories to create controls, widgets and activities in.

@x1B @jpommerening @jonaswjs Any thoughts on this?

**Comment by x1B** [comment]
I agree

**Comment by alex3683** [comment]
Implemented on `master` (`v2.2.0`).

### Upgrade information

If an application has a `laxar.config.js` with custom paths for `widgets` or `controls`, these will be used as default directories for newly created widgets or controls. Previously always `application/widgets` or `application/controls` resp. was used.
