### ISSUE TITLE
widgets: only generate .gitignore when adding project infrastructure

### ISSUE THREAD

**Issue by x1B** [LaxarJS/generator-laxarjs2#28]
Currently, the widget/activity generators create `.gitignore` files even when no standalone project is requested. 

However, the ignored files are 

 - already ignored by the project (test-results.xml, .sass-cache)
 - no longer relevant to laxarjs2 (.sass-cache).

So, the additional gitignore files are mostly noise now.

@jpommerening @alex3683 would you agree?

**Comment by alex3683** [comment]
Yo!

**Comment by jpommerening** [comment]
Ye~ho!

One `.gitignore` file per project should be enough :+1:

**Comment by x1B** [comment]
Implemented on `master` (`v2.3.0`).

### Upgrade Information

The LaxarJS2 generators for widgets, activities and controls will no longer create the redundant per-artifact`.gitignore` files, unless specifically asked for a project setup when creating an artifact.
