### ISSUE TITLE
Missing deps: chalk, mkdirp

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/generator-laxarjs2#29]
`chalk` and `mkdirp` are used but not declared as deps.
Might work on your machine anyway if you have these modules installed globally … I guess?

**Comment by x1B** [comment]
I guess this may have been working "by accident" if using npm 3 or higher because of the flat layout for transitive dependencies (though I cannot find `mkdirp` among them). We should definitely specify them, though.

**Comment by x1B** [comment]
Fixed on `master` (`v2.2.2`).
