### ISSUE TITLE
app generator: add favicon?

### ISSUE THREAD

**Issue by x1B** [LaxarJS/generator-laxarjs2#6]
This is more or less cosmetic: when browsing to a new application in Chrome with the developer tools open, I immediately see big red error (404 Not Found) because there is no favicon. Of course, this is not actually a problem, but it may be distracting to newbies.

Also, why not use the opportunity and shamelessly promote LaxarJS using our own favicon? 😈

**Comment by x1B** [comment]
Moving out of the milestone for now, as we're lacking a good favicon.ico file.

**Comment by alex3683** [comment]
Created a simple favicon file with transparency from the 32x32 pixel laxarjs.org version using some random online converter... Good enough for now, I'd say 😎

**Comment by alex3683** [comment]
Fixed on `master` (`v2.0.0`).
