### ISSUE TITLE
Make sure themes and layouts have a .json file.

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/generator-laxarjs2#9]
See LaxarJS/laxar-tooling#27 and LaxarJS/laxar-tooling#28.

We made descriptor files mandatory for all "directory" artifacts (everything except flows and pages), because we want to use the unmodified resolve-machanisms of webpack and webpack can not resolve directories.
Maybe we can review that decision in 2.1 or later by making use of `require.context()` or something like that, but for now, let's just add `theme.json` and `layout.json` files.

**Comment by x1B** [comment]
@jpommerening I don't think there even is a layout generator so far. We will need to adjust the core docs and the shop-demo tutorial, though.

**Comment by x1B** [comment]
@jpommerening ah, I forgot about the layouts created by the application generator...

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
